name: x_uri
description: A bridged's dynamic™ uri engine
version: 0.0.1
homepage: https://bridged.xyz/dynamic/uri

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
