name: flutter_remote_icon
description: remote icon loader for flutter
version: 0.0.3+6
author: softmarshmallow <woojoo@softmarshmallow.com>
homepage: https://github.com/softmarshmallow/remote-ui/tree/master/flutter/packages/flutter_remote_icon

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
