name: flutter_remote_ui
description: bridged's remote-ui for flutter app. bump your flutter project to enterprise level
version: 0.0.4+4
homepage: https://github.com/softmarshmallow/remote-ui/tree/master/flutter
repository: https://github.com/softmarshmallow/remote-ui

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://github.com/dnfield/flutter_svg
  flutter_svg: ^0.18.0

  flutter_remote_icon: 0.0.3+2

  # https://github.com/grpc/grpc-dart
  grpc: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
#  assets:
