name: x_action
description: a flutter uri based dynamic action handler
version: 0.0.1+4
homepage: https://github.com/softmarshmallow/dynamic/tree/master/flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.1.0

  x_uri: ^0.0.1+1
    # path: ../x_uri

  # FIXME remove this before release
  # flutter_modular: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.4.0
  build_runner: ^1.10.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
