name: flutter_remote_icon_generator
description: Icon mapping generator
version: 0.0.1+2
homepage: https://github.com/softmarshmallow/remote-ui/tree/master/flutter/packages/flutter_remote_icon/generator

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.10.0"

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.6
  analyzer: ^0.39.17
  flutter_remote_icon:
    path: ../


dev_dependencies:
  build_runner: ^1.10.2